#!/usr/bin/env bash
output() {
    while true
    do
        echo 'Working...'
        sleep 1
    done
}

echo 'Starting'
output &
output_pid=$!

while read -r line
do
    if [[ $line == 'stop' ]]; then
        echo 'Stopping'
        sleep 10
        kill -TERM $output_pid
        echo 'Done'
        break
    fi
done
